### ISSUE TITLE
OPTIX 3 License Violation

### ISSUE THREAD

**Issue by epsilonfive** [Overload02/Oxygen#2]
Hi there--noticed that Oxygen shares a lot of similarities to my own [OPTIX 3](https://github.com/epsilonfive/OPTIX_3). This, of course, isn't evidence that Oxygen uses code from it, but I did find a few instances of what are clearly OPTIX function names/defines in the source: [search for "optix"](https://github.com/search?q=repo%3AOverload02%2FOxygen%20optix&type=code).

OPTIX 3 is licensed under GPL3, which requires that changes to it be stated, the source be disclosed, and that the same license and copyright notice be included in any project that uses it. The issue isn't, of course, that the code has been copied, as the license explicitly allows it, but that these license conditions have not been met.

Hope we can reach a friendly agreement on this.

**Comment by Overload02** [comment]
Thank you for bringing this to my attention. I'll go ahead and keep this issue open until we reach an agreement.

**Comment by Overload02** [comment]
The issue has now been resolved.
